/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as MealIdRouteImport } from './routes/meal.$id'
import { Route as MemoriesDateRouteImport } from './routes/memories.$date'
import { Route as SettingsHelpRouteImport } from './routes/settings_.help'
import { Route as SettingsPrivacyDataRouteImport } from './routes/settings_.privacy-data'
import { Route as SettingsPrivacyPolicyRouteImport } from './routes/settings_.privacy-policy'
import { Route as SettingsSecurityRouteImport } from './routes/settings_.security'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesDateRoute = MemoriesDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => MemoriesRoute,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/settings_/help',
  path: '/settings/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyDataRoute = SettingsPrivacyDataRouteImport.update({
  id: '/settings_/privacy-data',
  path: '/settings/privacy-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyPolicyRoute = SettingsPrivacyPolicyRouteImport.update({
  id: '/settings_/privacy-policy',
  path: '/settings/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings_/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/meal/$id': typeof MealIdRoute
  '/memories/$date': typeof MemoriesDateRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/privacy-data': typeof SettingsPrivacyDataRoute
  '/settings/privacy-policy': typeof SettingsPrivacyPolicyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/meal/$id': typeof MealIdRoute
  '/memories/$date': typeof MemoriesDateRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/privacy-data': typeof SettingsPrivacyDataRoute
  '/settings/privacy-policy': typeof SettingsPrivacyPolicyRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/login': typeof LoginRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/google': typeof AuthGoogleRouteWithChildren
  '/meal/$id': typeof MealIdRoute
  '/memories/$date': typeof MemoriesDateRoute
  '/settings_/help': typeof SettingsHelpRoute
  '/settings_/privacy-data': typeof SettingsPrivacyDataRoute
  '/settings_/privacy-policy': typeof SettingsPrivacyPolicyRoute
  '/settings_/security': typeof SettingsSecurityRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/calendar'
    | '/login'
    | '/memories'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/terms'
    | '/auth/google'
    | '/meal/$id'
    | '/memories/$date'
    | '/settings/help'
    | '/settings/privacy-data'
    | '/settings/privacy-policy'
    | '/settings/security'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/calendar'
    | '/login'
    | '/memories'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/terms'
    | '/auth/google'
    | '/meal/$id'
    | '/memories/$date'
    | '/settings/help'
    | '/settings/privacy-data'
    | '/settings/privacy-policy'
    | '/settings/security'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/calendar'
    | '/login'
    | '/memories'
    | '/onboarding'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/settings'
    | '/terms'
    | '/auth/google'
    | '/meal/$id'
    | '/memories/$date'
    | '/settings_/help'
    | '/settings_/privacy-data'
    | '/settings_/privacy-policy'
    | '/settings_/security'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  CalendarRoute: typeof CalendarRoute
  LoginRoute: typeof LoginRoute
  MemoriesRoute: typeof MemoriesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AuthGoogleRoute: typeof AuthGoogleRouteWithChildren
  MealIdRoute: typeof MealIdRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsPrivacyDataRoute: typeof SettingsPrivacyDataRoute
  SettingsPrivacyPolicyRoute: typeof SettingsPrivacyPolicyRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$date': {
      id: '/memories/$date'
      path: '/$date'
      fullPath: '/memories/$date'
      preLoaderRoute: typeof MemoriesDateRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/settings_/help': {
      id: '/settings_/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/privacy-data': {
      id: '/settings_/privacy-data'
      path: '/settings/privacy-data'
      fullPath: '/settings/privacy-data'
      preLoaderRoute: typeof SettingsPrivacyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/privacy-policy': {
      id: '/settings_/privacy-policy'
      path: '/settings/privacy-policy'
      fullPath: '/settings/privacy-policy'
      preLoaderRoute: typeof SettingsPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/security': {
      id: '/settings_/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof AuthGoogleRoute
    }
  }
}

interface MemoriesRouteChildren {
  MemoriesDateRoute: typeof MemoriesDateRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesDateRoute: MemoriesDateRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

interface AuthGoogleRouteChildren {
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

const AuthGoogleRouteChildren: AuthGoogleRouteChildren = {
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}

const AuthGoogleRouteWithChildren = AuthGoogleRoute._addFileChildren(
  AuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  CalendarRoute: CalendarRoute,
  LoginRoute: LoginRoute,
  MemoriesRoute: MemoriesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AuthGoogleRoute: AuthGoogleRouteWithChildren,
  MealIdRoute: MealIdRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsPrivacyDataRoute: SettingsPrivacyDataRoute,
  SettingsPrivacyPolicyRoute: SettingsPrivacyPolicyRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
